apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryauc7476.azurecr.io/team5/tripviewer
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api.svc.cluster.local"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api.svc.cluster.local"
        - name: BING_MAPS_KEY
          value: "Aoqdvlg3dQXjjC-F2m6dAHGW1GHux5EWkhRhLS4_1EodY9uOuP5THr7u42xiERV8"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: tripviewer