# This is a SecretProviderClass example using aad-pod-identity to access the key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvsql-server
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: aa75c4d4-0a37-45f4-ad02-7c9c3cfe78e3   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: team5-secrets       # Set to the name of your key vault
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME
          objectType: secret             # object types: secret, key, or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""                    
    tenantId: 07be73d2-15e2-470a-a651-2365d6cd8898                # The tenant ID of the key vault